// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoveSoPickNPlace.Api.Entities;

#nullable disable

namespace RoveSoPickNPlace.Api.Migrations
{
    [DbContext(typeof(RoveSoPickNPlaceDatabase))]
    partial class RoveSoPickNPlaceDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");
#pragma warning restore 612, 618
        }
    }
}
